### PR TITLE
Traduction: english <-> french

### PR DESCRIPTION
**Pull request by MorpheusH3x**
This has been done:
- Translation of all existing content from French to English or vice versa
- Creation of the necessary files or modifications if existing but not respecting the syntax language-name.md
- Modification of the links between markdown files to allow the continuity of the existing documentation

### CODE REVIEW

**Comment by flesueur** [comment]
Hi ! First, big thanks for this contribution ! :tada: 

Would you mind to split this PR in two parts ?
1/ the translation of the tutorial (french -> english). As we talked before you started, this is indeed a great addition and I would merge it first easily
2/ then, on a dedicated issue or PR as you prefer, could we talk about the english -> french translations ? I agree that a french README, for instance, would be great, but I fear to have some inconsistencies in the future if we also translate, for instance, MI-IANA.md (which is a "reference/truth file"). Same for DETAILS.md. Thus, I'm not sure where to draw the line, and so a dedicated discussion on how to add translations, clearly show which files are authoritative (probably english ones), having a clear format to show which translations may be outdated, etc.

What do you think about that ?

Cheers
François

**Comment by flesueur** [comment]
I thought a bit about it. In fact, the french->english translation of the tutorial should probably become the reference, always up-to-date tutorial (named "TUTORIAL.md"). All english files, references, without language suffix. This would be one commit I could merge quickly.

Then, in a second time, we can try to maintain french translations of the different files (with fr.md suffix, or in a docs/fr/ subdirectory, not clear at the moment but I'd tend to think that the fr subdirectory would be better). We should probably find some clear way to express that only english are reference up-to-date files, others are best-effort. Besides this initial work, would you be interested to try to maintain the french translations in the long run ?

**Comment by flesueur** [comment]
well, all done ;). Thanks !!!

**Comment by MorpheusH3x** [comment]
I think the English version would be the one. But this raises the question of how to be sure that the French version reflects the latest modifications of the reference version, the English one.

I agree with you that a sub-folder for the French versions would make sense.
I will try to maintain the French versions as much as possible, let me know on Twitter if necessary.

**Pull request merged**
