### PR TITLE
SSHFS minor improvements

### PR DESCRIPTION
**Pull request by cnotin**

### CODE REVIEW

**Comment by flesueur** [comment]
That's great ! 
Still, there is still the bug that if you display commercial@target-commercial then the shared folder is not mounted (this bug was present before). Do you have any clue ?

**Comment by cnotin** [comment]
This issue looks like to be random...

**Comment by flesueur** [comment]
I'm not sure it is random. On my laptop, whether running mi-lxc on my linux or in the VM :
attach commercial@target-commercial -> shared is mounted
display commercial@target-commercial -> shared is not mounted, but if I do a "su commercial" then the shared folder appears...

**Comment by cnotin** [comment]
I'm rebuilding everything with all my changes and I'll check!

**Comment by flesueur** [comment]
I think I start to understand... In fact, it is mounted and then immediately unmounted, since display is non blocking... Ok, I'll have to think a bit about it ;)

**Pull request merged**
